Update new project section
django-commons/controls pull request #57
Opened 2024-10-06 18:56 UTC by cunla

2024-10-09 01:32 UTC, tim-schilling requested changes
A few small changes, but this looks good.

@cunla what do you think about asking the maintainers to create the release.yml and the test.pypi.org project before scheduling the call? Theoretically, we could also ask them all the various questions to make generating the repo config data easier too.

2024-10-09 01:32 UTC, tim-schilling commented on README.md
> +        - [ ] Repository has two environments: `pypi` and `testpypi`, see example [here][playground-enviroments]
```suggestion
        - [ ] Repository has two environments: `pypi` and `testpypi`, see example [here][playground-environments]
```

2024-10-09 01:32 UTC, tim-schilling commented on README.md
> +- [ ] pypi and test-pypi changes:
```suggestion
- [ ] PyPI and Test PyPI changes:
```

2024-10-09 01:32 UTC, tim-schilling commented on README.md
> +    - [ ] Add the release workflow to pypi's package publishing (and test-pypi's package publishing).
```suggestion
    - [ ] Add the release workflow to pypi.org's package publishing (and test.pypi.org's package publishing).
```

2024-10-09 01:32 UTC, tim-schilling commented on README.md
> +[playground-enviroments]: https://github.com/django-commons/django-commons-playground/settings/environments
```suggestion
[playground-environments]: https://github.com/django-commons/django-commons-playground/settings/environments
```

2024-10-09 02:10 UTC, ryancheley commented
> @cunla what do you think about asking the maintainers to create the release.yml and the test.pypi.org project before scheduling the call? Theoretically, we could also ask them all the various questions to make generating the repo config data easier too.

@tim-schilling  I was thinking about this after our call yesterday as well! I think it might be a good idea to ask the maintainers to do that OR to add in an extra 15 - 20 minutes (maybe more 🤷 ) to allow us time to do it on the call with them.

2024-10-09 02:18 UTC, tim-schilling commented
My opinion is that we should try to get the information beforehand to keep those meetings as short as we can.

I do think a video will help, but as we optimize the process, it'll keep needing to be updated.

2024-10-09 11:54 UTC, cunla commented
I am all for making it more efficient and this is a nice step forward.

Eventually, I hope we can get to a point where maintainers can transfer packages with our involvement only in the background. 
Theoretically, it is already possible: (1) approve PR to become member, (2) approve invite to PyPI, (3) approve PR to add repo to be managed.

Once the process stabilizes, I would like to do another video.

2024-10-12 21:03 UTC, tim-schilling approved these changes

2024-10-12 21:03 UTC, tim-schilling commented on README.md
> +- [ ] (project owner) PyPI project owner must add the Django Commons pypi's team members as owners in [PyPI][pypi],
```suggestion
- [ ] (project owner) PyPI project owner must add the Django Commons PyPI Admins as owners in [PyPI][pypi],
```

2024-10-12 21:03 UTC, tim-schilling commented on README.md
> +  (TODO: Determine how this works with transferring out of an org and into the Django Commons org)
```suggestion
```

2024-10-12 21:04 UTC, merged